### ISSUE TITLE
SVG exported from figma are not being rendered correctly

### ISSUE THREAD

**Issue by makinghappen** [zathras/jovial_svg#49] opened 2023-02-16 17:22 UTC
SVG exported from figma are not being rendered correctly

Gradients are not rendered:
![logo](https://user-images.githubusercontent.com/100151762/219439955-02efeb2e-c074-43ed-959f-d68601099ed9.svg)

One of the layers is not rendered
![wallpaper](https://user-images.githubusercontent.com/100151762/219439964-ba9b9a9d-2bd2-4312-98b1-c4157abdfc59.svg)

**Comment by zathras** [comment] 2023-02-16 18:14
**Some Things to Check**

If your issue is an SVG asset that doesn't parse, or doesn't look the same as when viewed with a browser:
* Have you read the "Supported SVG Profile" and "Goals and Package Evolution" sections of the README?  Cliff notes summary:  Not all SVG files are *expected* to work.
* Have you checked your file to see if it's valid?  See, for example, https://validator.w3.org/
* Have you narrowed it down to a reasonably concise and small SVG file that reproduces the issue?

**Comment by zathras** [comment] 2023-02-16 18:15
Duplicate of #25

**Closed by zathras** 2023-02-16 18:15 UTC
Labels: duplicate, Read README / bug template
